name: Build on macOS
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install makensis
        run: |
          brew update
          brew install makensis
      - name: Do build
        run: |
          makensis setup.nsi
      - name: Archive Installer
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: Installer.exe