name: Build on macOS
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install makensis
        run: |
          brew update
          brew install makensis
      - name: Do build
        run: |
          mkdir -p dist
          makensis alphanumeric_ascii.nsi
          makensis hiragana_utf8.nsi
      - name: Dump hex
        run: |
          hexdump -C dist/alphanumeric_ascii.exe > dist/alphanumeric_ascii_dump.txt
          hexdump -C dist/hiragana_utf8.exe > dist/hiragana_utf8_dump.txt
      - name: Archive Installer
        uses: actions/upload-artifact@v4
        with:
          name: Ventura
          path: dist
